---

- name: Create new domain in a new forest on the target host
  win_domain:
    dns_domain_name: "{{domain_name}}"
    safe_mode_password: 1Hope1NeverNeedThis!!
  delegate_to: "{{ setup_name }}-dc-2"