---

- name: Ensure a server is a domain controller
  win_domain_controller:
    dns_domain_name: "{{domain_name}}"
    domain_admin_user: "{{domain_admin_username}}"
    domain_admin_password: "{{domain_admin_password}}"
    safe_mode_password: 1Hope1NeverNeedThis!!
    state: domain_controller
  #delegate_to: "{{ setup_name }}-dc-1"