# tasks\roles.yml

- name: install windows feature AD-DS on DCs
  win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: yes
    include_sub_features: yes
  #when: ansible_facts.memtotal_mb == 2048
  register: adds_install

- name: reboot if AD DS was installed
  win_reboot:
  when: adds_install.restart_needed == true

#- name: List some variables
#  debug:
#    msg: "Domain name is {{domain_name}}, domain admin is {{domain_admin_username}} with password {{domain_admin_password}}"