---
# tasks\staticIP.yml

#- name: Set static IP on the Private interface
#  win_dsc:
#    resource_name: "xNetworking"
#    StaticIPAddress: "{{ansible_host}}"
#    DefaultGatawey: "{{ansible_interfaces[default_gateway]}}"
#    SubnetMask: 24
#- name: Set static IP and Gateway #radi ali prekine winrm i pukne timeout
#  win_command: powershell.exe -ExecutionPolicy ByPass -File c:/temp/ToDo/SetStaticIP.ps1
#  ignore_errors: true
#  register: IPchange
#- name: wait for server to come back online
#  local_action:
#    wait_for
#    host={{ inventory_hostname }}
#    port={{ ansible_port }}
#    delay=60
#    timeout=300
#    connect_timeout=65
#  when: IPchange.changed
- name: Set multiple lookup addresses on all visible adapters (usually physical adapters that are in the Up state)
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 8.8.8.8
    - "{{ansible_host}}"